version: "3"
services:
  es:
    image: elasticsearch:6.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
  kb:
    image: kibana:6.5.1
    ports:
      - "5601:5601"
    depends_on:
      - es
    links:
      - "es:elasticsearch"